### ISSUE TITLE
Support fir Cisco ASA Netflow

### ISSUE THREAD

**Issue by sppwf** [Graylog2/graylog-plugin-netflow#30]
Hi,

Do you think the plugin supports Cisco firewall - IOS 9.8?

Its seems that i have next issues:
	at org.graylog.plugins.netflow.flows.NetFlowFormatter.toMessageString(NetFlowFormatter.java:54) ~[?:?]
	at org.graylog.plugins.netflow.flows.NetFlowFormatter.toMessage(NetFlowFormatter.java:119) ~[?:?]
	at org.graylog.plugins.netflow.codecs.NetFlowCodec.lambda$decodeV9$2(NetFlowCodec.java:160) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_151]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_151]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_151]
	at org.graylog.plugins.netflow.codecs.NetFlowCodec.lambda$decodeV9$3(NetFlowCodec.java:161) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_151]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_151]
	at org.graylog.plugins.netflow.codecs.NetFlowCodec.decodeV9(NetFlowCodec.java:163) ~[?:?]
	at org.graylog.plugins.netflow.codecs.NetFlowCodec.decodeMessages(NetFlowCodec.java:134) ~[?:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:148) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
2018-02-07 09:08:45,042 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message RawMessage{id=7fdd18e0-0be6-11e8-8e32-86ed9180ca75, journalOffset=165877, codec=netflow, payloadSize=1673, timestamp=2018-02-07T09:08:45.038Z, remoteAddress=/10.161.84.192:10977} on input <5a7abcc01509a000010b2670>.
2018-02-07 09:08:45,042 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=7fdd18e0-0be6-11e8-8e32-86ed9180ca75, journalOffset=165877, codec=netflow, payloadSize=1673, timestamp=2018-02-07T09:08:45.038Z, remoteAddress=/10.161.84.192:10977}
java.lang.NullPointerException: null
	at org.graylog.plugins.netflow.flows.NetFlowFormatter.toMessageString(NetFlowFormatter.java:54) ~[?:?]
	at org.graylog.plugins.netflow.flows.NetFlowFormatter.toMessage(NetFlowFormatter.java:119) ~[?:?]
	at org.graylog.plugins.netflow.codecs.NetFlowCodec.lambda$decodeV9$2(NetFlowCodec.java:160) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_151]
	at java.util.Collections$2.tryAdvance(Collections.java:4717) ~[?:1.8.0_151]
	at java.util.Collections$2.forEachRemaining(Collections.java:4725) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_151]
	at org.graylog.plugins.netflow.codecs.NetFlowCodec.lambda$decodeV9$3(NetFlowCodec.java:161) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_151]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_151]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_151]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_151]
	at org.graylog.plugins.netflow.codecs.NetFlowCodec.decodeV9(NetFlowCodec.java:163) ~[?:?]
	at org.graylog.plugins.netflow.codecs.NetFlowCodec.decodeMessages(NetFlowCodec.java:134) ~[?:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:148) ~[graylog.jar:?]
	at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
	at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
	at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

Thanks
Sergiu Plotnicu

**Comment by joschi** [comment]
@sppwf
Which version of the plugin are you using?
Which version of Graylog are you using?
Could you provide a [pcap](https://en.wikipedia.org/wiki/Pcap) of the NetFlow packets (recorded with Wireshark or tcpdump) so that we can reproduce the issue?

**Comment by sppwf** [comment]
Hi,

I am using latest plugin version 0.1.1
Graylog Version is - 2.4.3 
I am using containerized graylog. 

Attached the Flow pcap. just one packet, hope is ok
[asa_neflow.zip](https://github.com/Graylog2/graylog-plugin-netflow/files/1706115/asa_neflow.zip)

Thanks

**Comment by joschi** [comment]
@sppwf I'm afraid that a single packet is not enough.

Ideally, the pcap would contain all of the various NetFlow v9 packet types (i. e. Template FlowSet and Data FlowSet).

**Comment by sppwf** [comment]
Please find attached more packets.
hope this helps
[asa_neflow.zip](https://github.com/Graylog2/graylog-plugin-netflow/files/1716414/asa_neflow.zip)

**Comment by GMarciales** [comment]
Hi,

I am into the same issue. Mine works perfectly with IOS, but it is unable to work with ASA. Also, I installed another NetFlow collector, and this works  fine with both exporters (IOS ans ASA). My ASA runs asa991-lfbff-k8.spa, which is the latest version. Also, I have tested with several previous ASA releases, and I have gotten the same result. I am running Graylog v2.4.3+2c41897.

Any advice?

How can contribute?

Regards.

**Comment by mariusgeonea** [comment]
I'm having the same problem, i receive the packets in graylog but when i click on show received messages nothing is displayed..........

any idea how to fix this one???

![image](https://user-images.githubusercontent.com/36670465/38930396-0a1ce868-4310-11e8-9b9a-3c38b72a2ea9.png)
![image](https://user-images.githubusercontent.com/36670465/38930402-1420c938-4310-11e8-8f36-5fd652616156.png)

**Comment by stealthey** [comment]
I've got the exact same issue, used both OVA & manually installed on Ubuntu.

excerpt from logs:

> 2018-05-24T21:53:09.137Z ERROR [DecodingProcessor] Unable to decode raw message RawMessage{id=d8c842e0-5f9c-11e8-bd06-000c29ce27ac, journalOffset=2507, codec=netflow, payloadSize=243, timestamp=2018-05-24T21:53:09.134Z, remoteAddress=/10.10.5.3:29124} on input <5b073049268aa40ef2fc2db4>.
> 2018-05-24T21:53:09.138Z ERROR [DecodingProcessor] Error processing message RawMessage{id=d8c842e0-5f9c-11e8-bd06-000c29ce27ac, journalOffset=2507, codec=netflow, payloadSize=243, timestamp=2018-05-24T21:53:09.134Z, remoteAddress=/10.10.5.3:29124}

**Comment by zarbam** [comment]
I am also having the same issue on asa ver 9.8.2

**Comment by mariusgeonea** [comment]
one way is to use logstash as a workarround, in my case i decided to go for syslog with grok patterns, netflow btw will increase your CPU usage on ASA....

**Comment by jalogisch** [comment]
I'll just copy the text from: https://github.com/Graylog2/graylog2-server/issues/4865#issuecomment-420155157

Please be aware that we need samples to test our tool. Yes out there are collections like http://packetlife.net/captures/protocol/udp/ but you as user would help us if you provide sample data.

We as developer do not own all the devices you have and do not count on the vendor that they will provide us with the samples of your device.

> provide a pcap of the NetFlow packets (recorded with Wireshark or tcpdump) so that we can reproduce the issue?

**Comment by iT3han** [comment]
Can confirm this issue

ASA 9.6
Graylog 2.4.6
Netflow Plugin shipped with Graylog 2.4.6

`2018-09-14 07:49:00,775 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Unable to decode raw message RawMessage{id=e1267a48-b7e1-11e8-8485-7240a49d5857, journalOffset=1397263219, codec=netflow, payloadSize=1666, timestamp=2018-09-14T05:49:00.772Z, remoteAddress=/192.168.77.14:59063} on input <5b9b45db8573531d1ec49d2f>.
2018-09-14 07:49:00,776 ERROR: org.graylog2.shared.buffers.processors.DecodingProcessor - Error processing message RawMessage{id=e1267a48-b7e1-11e8-8485-7240a49d5857, journalOffset=1397263219, codec=netflow, payloadSize=1666, timestamp=2018-09-14T05:49:00.772Z, remoteAddress=/192.168.77.14:59063}
java.lang.NullPointerException: null
        at org.graylog.plugins.netflow.flows.NetFlowFormatter.toMessageString(NetFlowFormatter.java:54) ~[?:?]
        at org.graylog.plugins.netflow.flows.NetFlowFormatter.toMessage(NetFlowFormatter.java:119) ~[?:?]
        at org.graylog.plugins.netflow.codecs.NetFlowCodec.lambda$decodeV9$2(NetFlowCodec.java:160) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_181]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_181]
        at org.graylog.plugins.netflow.codecs.NetFlowCodec.lambda$decodeV9$3(NetFlowCodec.java:161) ~[?:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_181]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_181]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_181]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_181]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_181]
        at org.graylog.plugins.netflow.codecs.NetFlowCodec.decodeV9(NetFlowCodec.java:163) ~[?:?]
        at org.graylog.plugins.netflow.codecs.NetFlowCodec.decodeMessages(NetFlowCodec.java:134) ~[?:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.processMessage(DecodingProcessor.java:148) ~[graylog.jar:?]
        at org.graylog2.shared.buffers.processors.DecodingProcessor.onEvent(DecodingProcessor.java:91) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:74) [graylog.jar:?]
        at org.graylog2.shared.buffers.processors.ProcessBufferProcessor.onEvent(ProcessBufferProcessor.java:42) [graylog.jar:?]
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:143) [graylog.jar:?]
        at com.codahale.metrics.InstrumentedThreadFactory$InstrumentedRunnable.run(InstrumentedThreadFactory.java:66) [graylog.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]`

[asa_9-6_netflow.zip](https://github.com/Graylog2/graylog-plugin-netflow/files/2382083/asa_9-6_netflow.zip)

**Comment by mariusgeonea** [comment]
> I'll just copy the text from: [Graylog2/graylog2-server#4865 (comment)](https://github.com/Graylog2/graylog2-server/issues/4865#issuecomment-420155157)
> 
> Please be aware that we need samples to test our tool. Yes out there are collections like http://packetlife.net/captures/protocol/udp/ but you as user would help us if you provide sample data.
> 
> We as developer do not own all the devices you have and do not count on the vendor that they will provide us with the samples of your device.
> 
> > provide a pcap of the NetFlow packets (recorded with Wireshark or tcpdump) so that we can reproduce the issue?

Hi Jan,

i could work with you regarding the netflow v9 because this is what cisco ASA firewalls are using.

do you wanna to have live meeting for this one?

Thanks,
Marius.

**Comment by ebnozn** [comment]
I can also furnish some PCAPs for an ASA v9 NetFlow if this would help.  Cisco ASR router Netflows decoded just fine.  I am also tracking the bug with Fortigate Netflow parsing issues as well :(

**Comment by lennartkoopmann** [comment]
Everyone experiencing this issue: Could you please try if it still occurs with Graylog v3.0? The final v3.0.0 package is announced tomorrow but you can get started with it already by following the RC installation guides.

@mpfz0r fixed a lot of parsing issues here: Graylog2/graylog2-server#5507

**Comment by themcv** [comment]
No go on my end. Getting a test environment setup so that I can upload pcap files. 

Hopefully someone can beat me to uploading them.

**Comment by mpfz0r** [comment]
@themcv thanks! If you do, make sure your pcap contains template records as well.
I don't know how often a Cisco device sends out template records, maybe capture a few minutes
if it's not too big.

**Comment by themcv** [comment]
@mpfz0r Will do. I have to pull and reset a spare 5516-x to get the environment exactly the same. Hopefully i can get it done today to give you guys some data.

**Comment by themcv** [comment]
@mpfz0r I am sending you an email with the PCAP file right now. Let me know if you get it!

**Comment by themcv** [comment]
@mpfz0r Is the mpf+gh@mailq.de the best email to send it to?

**Comment by mpfz0r** [comment]
> @mpfz0r Is the [mpf+gh@mailq.de](mailto:mpf+gh@mailq.de) the best email to send it to?

Yep, that's fine. Thank you!

**Comment by themcv** [comment]
@mpfz0r Great, it is sent.

**Comment by kkoole** [comment]
@mpfz0r Hi, I've been running Graylog 2.5.x in production for a while now with a Cisco ASA 5525-X on ASA 9.6.3, recently I have upgraded to Graylog 3.0 GA. I am also experiencing these same issues, if you guys need more help from us the users please let me know!

**Comment by mpfz0r** [comment]
@kkoole Are you saying that it worked on 2.5 and does not on 3.0 anymore?
